name: 🔐 SSH Deploy to VPS and Pull Image

on:
  workflow_run:
    workflows: ["📦 Push"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: SSH to VPS and pull image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.USERNAME }}/${{ secrets.USERNAME }}
            docker compose pull
            docker compose up -d
